# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='second_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='first_app.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='first_app.User'),
        ),
    ]
